---
kind: pipeline
type: kubernetes
name: OpsData-Perf-Testing

platform:
  os: linux
  arch: amd64

steps:

  - name: Customize-kube-files
    image: supporttools/kube-builder:32
    pull: true
    environment:
      APPENV: ${DRONE_COMMIT_BRANCH}
    commands:
      - bash ./deploy.sh

  - name: Docker-Build-Login
    image: plugins/docker
    settings:
      purge: false
      registry: registry.support.tools
      repo: registry.support.tools/opsdata-perf/login
      dockerfile: ./Login/Dockerfile
      context: ./Login/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "registry.support.tools/opsdata-perf/login:latest"
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password

  - name: Deploy-to-Dev
    image: supporttools/kube-builder:32
    pull: true
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: b1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
    commands:
      - kubectl apply -n opsdata-perf-dev -f ./deployment-ready/login-dev.yaml      

  - name: Deploy-to-Staging
    image: supporttools/kube-builder:32
    pull: true
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: b1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
    commands:
      - kubectl apply -n opsdata-perf-staging -f ./deployment-ready/login-staging.yaml
    when:
     event:
     - deployment
     - promote
     target:
     - staging

  - name: Deploy-to-Production
    image: supporttools/kube-builder:32
    pull: true
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: b1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
    commands:
      - kubectl apply -n opsdata-perf-production -f ./deployment-ready/login-production.yaml
    when:
     event:
     - deployment
     - promote
     target:
     - production

node_selector:
  beta.kubernetes.io/arch: amd64
  drone-runner: true

image_pull_secrets:
- regcreds